entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: /certs/nextcloud.crt
      keyFile: /certs/nextcloud.key
    - certFile: /certs/office.crt
      keyFile: /certs/office.key
    - certFile: /certs/notes.crt
      keyFile: /certs/notes.key
    - certFile: /certs/auth.crt
      keyFile: /certs/auth.key

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true

certificatesResolvers:
  localcert:
    acme:
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: admin@localhost
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
